### ISSUE TITLE
Any particular reason why the order of the spec tests is randomized?

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/dynamic-orm-lab#11]
I commented out

``` ruby
config.order = :random
```

and it made the tests much easier to follow.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by Traci7822** [comment]
Issue still exists

commenting out the `config.order = :random` line resolves the issue:

From student's console when running fail fast tests:

> Randomized with seed 39604
> 
> Student
>   inheritance
>     inherits from InteractiveRecord class
>   .column_names
>     returns an array of SQL column names (FAILED - 1)
> 
> Failures:
> 
>   1) Student.column_names returns an array of SQL column names
>      Failure/Error: expect(Student.column_names).to eq(["id", "name", "grade"])
>      
>      NoMethodError:
>        undefined method &#96;column_names' for Student:Class
>      # ./spec/student_spec.rb:43:in &#96;block (3 levels) in <top (required)>'
> 
> Finished in 0.00755 seconds (files took 0.21075 seconds to load)
> 2 examples, 1 failure
> 
> Failed examples:
> 
> rspec ./spec/student_spec.rb:42 # Student.column_names returns an array of SQL column names
> 
> Randomized with seed 39604
> 
> Randomized with seed 1762
> 
> Student
>   .find_by
>     accounts for when an attribute value is an integer (FAILED - 1)
> 
> Failures:
> 
>   1) Student.find_by accounts for when an attribute value is an integer
>      Failure/Error: Student.new({name: "Susan", grade: 10}).save
>      
>      ArgumentError:
>        wrong number of arguments (given 1, expected 0)
>      # ./spec/student_spec.rb:120:in &#96;initialize'
>      # ./spec/student_spec.rb:120:in &#96;new'
>      # ./spec/student_spec.rb:120:in &#96;block (3 levels) in <top (required)>'
> 
> Finished in 0.00503 seconds (files took 0.16581 seconds to load)
> 1 example, 1 failure
> 
> Failed examples:
> 
> rspec ./spec/student_spec.rb:119 # Student.find_by accounts for when an attribute value is an integer
> 
> Randomized with seed 1762

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/dynamic-orm-lab/commit/1d21e0cb912db0aeb214f0c6f198a4984a6b47b9.
