### ISSUE TITLE
remove duplicate database connection setting from the InteractiveRecord class

### ISSUE THREAD

**Issue by nicolefederici** [learn-co-curriculum/dynamic-orm-lab#13]
this is in the solution to this lab:

The  `DB[:conn].results_as_hash = true` should be removed. It's already stated in config/environment.rb and then required by lib/interactive_record.rb. Confusing. 

``` ruby
def self.column_names
    DB[:conn].results_as_hash = true

    sql = "pragma table_info('#{table_name}')"

    table_info = DB[:conn].execute(sql)
    column_names = []
    table_info.each do |row|
      column_names << row["name"]
    end
    column_names.compact
  end
```

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We removed the duplicate `results_as_hash` configuration call.

As always thank you for contributing.
