### ISSUE TITLE
Suggestion: make the find_by rspec more robust

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/dynamic-orm-lab#14]
I would suggest making the find_by rspec more robust.

The following wrong answer passes the tests:

  def self.find_by(attribute)
    sql = "SELECT * FROM #{self.table_name} WHERE '#{attribute}' = '#{attribute}'"
    DB[:conn].execute(sql)
  end

...because the tests are only creating one student, so they're failing to detect wrong answers that include false positives.

The following would seem to do the trick:

    it 'accounts for when an attribute value is an integer' do
      Student.new({name: "Geraldine", grade: 9}).save
      Student.new({name: "Susan", grade: 10}).save
      Student.new({name: "Sammy", grade: 11}).save
      expect(Student.find_by({grade: 10})).to eq([{"id"=>1, "name"=>"Susan", "grade"=>10, 0=>1, 1=>"Susan", 2=>10}])
    end

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We incorporated your suggestion.

As always thank you for contributing.
