### ISSUE TITLE
The test for attr_accessor doesn't check for a hard-coded attr_accessor

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/dynamic-orm-lab#16]
Hello. I found a little bug in the test for attr_accessor. Even when I hard code the attr_accessor (instead of creating attr_accessors for each column name) as shown below, the test still passes.

My suggestion would be to make an additional test that makes sure that the Student class calls the Student.column_names method to assign its attributes, rather than hard-coding the attr_accessor. However, this may require you to add a new column to the students table, so I'm not sure if it's worth the hassle.

Either way, thanks a lot for looking into this!

Sdcrouse

![image](https://user-images.githubusercontent.com/38870640/49909122-64eeed80-fe32-11e8-97f9-8b3e470440c3.png)

**Comment by sgharms** [comment]
Hm, I think you're right on this. Trying to test metaprogramming is darn difficult (part of the risks of doing it professionally). I'll add it as something to loop back to when we review this section next year. Thanks!

**Comment by Sdcrouse** [comment]
No problem. And no worries either way.
