### ISSUE TITLE
Broken Rspec

### ISSUE THREAD

**Issue by Luiszaba** [learn-co-curriculum/dynamic-orm-lab#17]
The rspec is broken and does not read the solutions for self.find_by_name, save and self.find_by.
I had to comment out the rspec to get the lab to pass

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
