### ISSUE TITLE
Specs may be using out of date with newer sqlite3 

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/dynamic-orm-lab#18]
__Summary__ Student was failing tests based on desired `#DB[:conn].execute` return values to have redundant values, with the keys being 0,1,2..etc for the redundant values.

__Fix__ We took out all the redundant value pairs with numeric keys, and all of the tests passed. The code was all correct, so I think that it is possible that sqlite3 returns different values for `#execute` than it did when the lab was first made

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
