### ISSUE TITLE
tests assume different version of results_as_hash

### ISSUE THREAD

**Issue by tan-nate** [learn-co-curriculum/dynamic-orm-lab#20]
results_as_hash no longer returns integer key values, it seems

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
