### ISSUE TITLE
Hello, a previously entered issue was closed, but it is still happening

### ISSUE THREAD

**Issue by regilfillan** [learn-co-curriculum/dynamic-orm-lab#22]
Hello,

Other students brought up this issue (11 days ago according to the closed entries) and it was marked as closed/solved, but several students are still experiencing the issue:

"The following spec tests have extra data, it looks like another copy of the data where the keys are indices of the array...its pretty weird. But I am pretty sure they do not belong. Specifically the save, find_by, and find_by_name have this included in their hash in the test: #, 0=>1, 1=>"Susan", 2=>10"

"results_as_hash no longer returns integer key values, it seems"

"Summary Student was failing tests based on desired #DB[:conn].execute return values to have redundant values, with the keys being 0,1,2..etc for the redundant values.
Fix We took out all the redundant value pairs with numeric keys, and all of the tests passed. The code was all correct, so I think that it is possible that sqlite3 returns different values for #execute than it did when the lab was first made"

**Comment by maxwellbenton** [comment]
Hi @regilfillan,

Thank you for spotting this and providing feedback. We've looked into this issue and it looks like the updates had only made it to the solution branch. The updates have now been applied to the master branch and the extra data has been removed from the tests. 

Thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. If you do not believe that this issue has been addressed, please re-open this issue. 💙
