### ISSUE TITLE
I am using Nitrous IDE on windows Machine!

### ISSUE THREAD

**Issue by hide83** [learn-co-curriculum/dynamic-orm-lab#9]
I have been using Nitrous IDE on windows machine and no matter what gems i install or whatever i do i keep getting this error 
/home/nitrous/code/labs/dynamic-orm-lab-v-000/lib/interactive_record.rb:2:in `require': cannot load such file -- active_support/inflector (LoadError)
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/lib/interactive_record.rb:2:in`<top (required)>'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/lib/student.rb:3:in `require_relative'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/lib/student.rb:3:in`<top (required)>'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/spec/spec_helper.rb:2:in `require_relative'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/spec/spec_helper.rb:2:in`<top (required)>'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `require'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in`block in requires='
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in`requires='
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_i
nto'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in`each'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in`configure'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in`run'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in`invoke'
        from /home/nitrous/code/labs/dynamic-orm-lab-v-000/.bundle/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/rspec:23:in`load'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/rspec:23:in `<main>'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/ruby_executable_hooks:15:in`eval'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/ruby_executable_hooks:15:in `<main>'

Even Learn Experts tried helping me but no success so i was suggested to raise an issue and move ahead and come back to this lab later. Please help me with this. Thanks :)

**Comment by pletcher** [comment]
Hi @hide83, sorry you're running into an issue. The best thing might be to try the Learn IDE: https://learn.co/ide -- you should see a walkthrough explaining how to use it once you've downloaded it and set it up. No more Nitrous!
